"""Generic models for multi-agent responses."""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class AgentResponse:
    """Standard response from any multi-tool agent.

    Attributes:
        response_text: Final natural language response generated by the LLM.
        tool_results: Intermediate results from each tool {name: json_string}.
        metadata: Optional additional information (timestamps, metrics, etc).
    """

    response_text: str
    tool_results: dict[str, str]
    metadata: dict[str, Any] = field(default_factory=dict)
